- name: Ensure intelephense directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/intelephense"
    mode: 0700
    state: directory
  tags:
    - keys
    - intelephense
    
- name: Install intelephense key
  copy:
    src: "./keys/intelephense"
    dest: "{{ lookup('env', 'HOME') }}/intelephense/licence.txt"
    mode: 0600
  tags:
    - keys
    - intelephense
    
