- name: Change shell to zsh
  shell: chsh -s $(which zsh)

- name: Get oh-my-zsh script
  become: true
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ lookup('env', 'HOME') }}/oh_my_zsh_install.sh"
    mode: '0755'
  tags:
    - zsh
    - install

- name: Install Oh-My-Zsh
  command: "{{ lookup('env', 'HOME') }}/oh_my_zsh_install.sh --unattended --keep-zshrc"
  register: zsh_install
  tags:
    - zsh
    - install

- name: Delete oh-my-zsh script
  file:
    path: ~/oh_my_zsh_install.sh
    state: absent
  tags:
    - zsh
