- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - dotfiles
    
- name: Get zplug script
  become: true
  get_url:
    url: https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
    dest: "{{ lookup('env', 'HOME') }}/zplug.sh"
    mode: '0755'
  tags:
    - zsh
    - install

- name: Install zplug
  command: "{{ lookup('env', 'HOME') }}/zplug.sh --unattended --keep-zshrc"
  register: zsh_install
  tags:
    - zsh
    - install

- name: Delete zplug script
  file:
    path: ~/zplug.sh
    state: absent
  tags:
    - zsh
    - install
